# Generated by Django 3.1.1 on 2020-09-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0002_auto_20200917_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testuser',
            old_name='user_nmae',
            new_name='user_name',
        ),
    ]
