# Generated by Django 3.1.1 on 2020-09-21 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0002_bbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 6, 37, 54, 364131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='viewcnt',
            field=models.IntegerField(default=0),
        ),
    ]
