# Generated by Django 3.1.1 on 2020-09-24 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0003_auto_20200921_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 1, 13, 41, 965445, tzinfo=utc)),
        ),
    ]
